sudo: required

language: c

services:
  - docker

before_script:
  - docker build --tag devel -f Dockerfile.dev .

script:
  - docker create --name develcontainer devel
  - mkdir RNAlien
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.4.3/RNAlien-1.7.2/x/RNAlien/build/RNAlien/RNAlien RNAlien
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.4.3/RNAlien-1.7.2/x/RNAlienStatistics/build/RNAlienStatistics/RNAlienStatistics RNAlien
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.4.3/RNAlien-1.7.2/x/cmsearchToBed/build/cmsearchToBed/cmsearchToBed RNAlien
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.4.3/RNAlien-1.7.2/x/RNAcentralHTTPRequest/build/RNAcentralHTTPRequest/RNAcentralHTTPRequest RNAlien
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.4.3/RNAlien-1.7.2/x/RNAlienScan/build/RNAlienScan/RNAlienScan RNAlien
  - cp LICENSE RNAlien
  - tar -cvzf RNAlien.tar.gz RNAlien


deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: "RNAlien.tar.gz"
  on:
    tags: true
