flags: {}
packages:
- '.'
compiler-check: newer-minor
extra-deps:
- either-unwrap-1.1
- ViennaRNAParser-1.2.6
- ClustalParser-1.1.3
- EntrezHTTP-1.0.0
- Taxonomy-1.0.1
- hierarchical-clustering-0.4.6
- graphviz-2999.18.0.2
resolver: lts-3.20
