flags: {}
packages:
- '.'
extra-deps:
- EntrezHTTP-1.0.3
- BlastHTTP-1.2.1  
- ParsecTools-0.0.2.0
- RNAlien-1.2.5
- Taxonomy-1.0.2
- ViennaRNAParser-1.3.1

compiler-check: newer-minor
resolver: lts-6.22
